


#let balance-sheet-summary(
  cash,
  ar,
  inventory,
  ppe,
  ap,
  debt,
  equity,
) = table(
  columns: 2,
  inset: (x: 1em, y: 0.5em),
  align: center + horizon,
  table.cell(colspan: 2, fill: black.transparentize(75%), [Statement of Balance]),
  table.cell(
    [Assets],
    fill: black.transparentize(75%),
  ),
  table.cell(
    [Liabilities],
    fill: black.transparentize(75%),
  ),
  [
    Cash\
    *#cash*
  ], 
  [
    A/P\ 
    *#ap*
  ],
  [
    A/R\ 
    *#ar*
  ], [
    Debt\ 
    *#debt*
  ],
  [
    Inventory\ 
    *#inventory*
  ], 
  table.cell(rowspan: 2, [
    Equity\ *#equity*
  ]),
  [
    PP&E\ 
    *#ppe*
  ],
)

#let income-statement(
  revenue,
  cogs,
  sga,
  da,
  interest,
  tax,
) = [
  #let gross-profit = revenue - cogs
  #let ebitda = gross-profit - sga
  #let ebit = ebitda - da
  #let ebt = ebit - interest
  #let np = ebt - tax

  #table(
    columns: 2,
    inset: (x: 1em, y: 0.5em),
    align: left,
    stroke: (x, y) => (
      bottom: if y in (0, 2, 4, 6, 8, 10, 11) {black + 1pt},
      right: if x in (1,) {black + 1pt},
      left: if x in (0,) {black + 1pt},
    ),
    table.cell(
      colspan: 2,
      fill: black.transparentize(75%),
      stroke: black,
      [Income Statement]
    ),
    [Revenue], 
    [#revenue],
    [GoGS], 
    [#text(fill: red, weight: "semibold")[#cogs]],
    [Gross Profit], 
    [#gross-profit],
    [SGA], 
    [#text(fill: red, weight: "semibold")[#sga]],
    [EBITBA], 
    [#ebitda],
    [D&A], 
    [#text(fill: red, weight: "semibold")[#da]],
    [EBIT], 
    [#ebit],
    [Interest], 
    [#text(fill: red, weight: "semibold")[#interest]],
    [EBT], 
    [#ebt],
    [Tax],
    [#text(fill: red, weight: "semibold")[#tax]], 
    [NP],
    [#np]

  )
]

#let t-account(title, ..content) = table(
  columns: (1fr, 1fr),
  inset: 1em,
  stroke: (x, y) => (
    bottom: if y == 0 {black + 1pt},
    right: if y > 0 and x == 0 {black + 1pt},
  ),
  table.cell(
    colspan: 2,
    [#title]
  ),
  ..content
)

#let balance-sheet(
  assets: (),
  liabilities: (),
) = table(
  columns: (1fr, 1fr),
  inset: 1em,
  table.cell(
    colspan: 2, 
    fill: black.transparentize(75%), 
    [Statement of Balance]
  ),
  table.cell(
    [Assets],
    fill: black.transparentize(75%),
  ),
  table.cell(
    [Liabilities & Equity],
    fill: black.transparentize(75%),
  ),
  table(
    columns: 2,
    stroke: none,
    ..assets.map(a => table.cell(a))
  ),
  table(
    columns: 2,
    stroke: none,
    ..liabilities.map(l => table.cell(l))
  )
)

#let vlabel(body) = rotate(-90deg, reflow: true, body)

#let statement-cash-flow(
  
) = table(
  columns: 3,
  inset: (x: 1em, y: 0.5em),
  align: left,
  table.cell(
    colspan: 3,
    fill: black.transparentize(75%),
    [Statement of Cash FLow]
  ),
  table.cell(
    rowspan: 6, 
    fill: black.transparentize(75%), 
    align: center + horizon, 
    vlabel[Operating]
  ),
  [Net Profit], [],
  [D&A], [],
  [A/R], [],
  [Inventory], [],
  [A/P], [],
  [Cash generated by Operations], [],
  table.cell(
    rowspan: 2, 
    fill: black.transparentize(75%), 
    align: center + horizon, 
    vlabel[Investing]
  ),
  [New Investment], [],
  [Cash used in Investement], [],
  table.cell(
    rowspan: 3, 
    fill: black.transparentize(75%),
    align: center + horizon, 
    vlabel[Financing]
  ),
  [Cash raised from Equity], [],
  [Chnages in Debt], [],
  [Cash used in financing], [],
  table.cell(stroke: none, []),
  table.cell(
    fill: black.transparentize(75%), 
    [Net cash]
  ),
)